/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ChatReceiverIdImport } from './routes/chat.$receiverId'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ChatReceiverIdRoute = ChatReceiverIdImport.update({
  id: '/chat/$receiverId',
  path: '/chat/$receiverId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/chat/$receiverId': {
      id: '/chat/$receiverId'
      path: '/chat/$receiverId'
      fullPath: '/chat/$receiverId'
      preLoaderRoute: typeof ChatReceiverIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/chat/$receiverId': typeof ChatReceiverIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/chat/$receiverId': typeof ChatReceiverIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/chat/$receiverId': typeof ChatReceiverIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/chat/$receiverId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chat/$receiverId'
  id: '__root__' | '/' | '/chat/$receiverId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  ChatReceiverIdRoute: typeof ChatReceiverIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  ChatReceiverIdRoute: ChatReceiverIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/chat/$receiverId"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/chat/$receiverId": {
      "filePath": "chat.$receiverId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
